FROM node:15

ENV REACT_APP_CLIENT_ROOT_URL=http://localhost:5000/
ENV REACT_APP_SERVER_ROOT_URL=http://localhost:5000/

COPY server/package*.json ./

RUN npm install

COPY server/ .

ADD client ./client

RUN cd client && npm install && npm run build && mkdir -p ../build && mv build/* ../build && cd .. && rm -R client

EXPOSE 5000

CMD [ "node", "app.js" ]
