# Spins up containers to run locally

version: "3.3"
services:
    api_server_and_client:
        depends_on: 
            - mongo
        build:
            context: ../
            dockerfile: docker/Dockerfile.api_server_and_client
        environment: 
            PORT: 5000
            MONGODB_URI: mongodb://root:password@mongo:27017
            STREAM_SERVER_ROOT_URL: http://streaming_server:5001/
        ports:
            - "5000:5000"

    streaming_server:
        build:
            context: ../
            dockerfile: docker/Dockerfile.streaming_server
        ports:
            - "5001:5001"

    mongo:
        build: ./mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: cassettenet
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./mongo/init-db.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    # GUI interface for mongo
    mongo-express:
        depends_on: 
            - mongo
        image: mongo-express
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo
        ports: 
            - 5002:8081

volumes:
    mongo:
